Add controllers
Jariodson/java-shareit pull request #1
Opened 2024-04-29 18:45 UTC by Jariodson

2024-04-30 19:04 UTC, dgumich requested changes

2024-04-30 19:04 UTC, dgumich commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                                              @RequestBody Item item,
Классы ДТО используются не только в качестве ответа, но и в качестве входных данных.
Item - это класс-модель, он будет работать только с бд/сервисов.
Так что исправь, что бы контроллеры принимали ДТО классы, а не модели.

2024-04-30 19:04 UTC, dgumich commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorageImpl.java
> +public class ItemStorageImpl implements ItemStorage {
Молодец, что заморочился с БД.
По ТЗ этого  делать не надо было, так же подошла бы хеш мапа.
В следующем уроке будете проходить Spring JPA

2024-04-30 19:04 UTC, dgumich commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public ResponseEntity<UserDto> updateUser(@RequestBody User user,
Не забывай, что если ты хочешь, что бы спринг провалидировал входящие объект, надо добавить аннотацию @Valid

2024-04-30 19:32 UTC, Jariodson commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            throw new ValidationException("Пользователь с ID" + userId + " не найден!");
в postman тестах странная логика. При работе с пользователем, если используем метод validateUserId, то код ответа должен быть один, а при работе с item, где используется этот же метод уже код ответа должен быть другим в случае ошибки

2024-04-30 19:32 UTC, Jariodson commented on src/main/java/ru/practicum/shareit/ErrorHandler.java
> +        log.warn("Ошибка! {}", throwable.getMessage());
исправил

2024-05-01 08:50 UTC, Jariodson commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                                              @RequestBody Item item,
исправил

2024-05-01 08:51 UTC, Jariodson commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorageImpl.java
> +public class ItemStorageImpl implements ItemStorage {
понял

2024-05-01 09:19 UTC, Jariodson commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public ResponseEntity<UserDto> updateUser(@RequestBody User user,
исправил

2024-05-02 00:53 UTC, dgumich approved these changes

2024-05-02 05:59 UTC, merged