Add bookings
Jariodson/java-shareit pull request #2
Opened 2024-05-15 13:35 UTC by Jariodson

2024-05-16 14:33 UTC, dgumich requested changes

2024-05-16 14:33 UTC, dgumich commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (booking.getItem().getUser().getId().equals(userId) || booking.getBooker().getId().equals(userId)) {
Такие длинные проверки лучше выносить в отдельные методы. Так код становится понятней

2024-05-16 14:33 UTC, dgumich commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            if (Status.REJECTED.equals(Status.valueOf(booking.getStatus()))) {
Энамы сравнивают через ==

2024-05-17 07:59 UTC, Jariodson commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    private String status;
исправил

2024-05-17 08:01 UTC, Jariodson commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +
исправил

2024-05-17 09:04 UTC, Jariodson commented on src/main/java/ru/practicum/shareit/booking/BookingStorage.java
> +    @Query("SELECT b FROM Booking b " +
исправил

2024-05-18 03:26 UTC, dgumich approved these changes

2024-05-20 18:26 UTC, merged