Add item requests
Jariodson/java-shareit pull request #3
Opened 2024-06-25 17:52 UTC by Jariodson

2024-06-27 12:03 UTC, YazykovMikhail requested changes

2024-06-28 07:42 UTC, Jariodson commented on src/main/java/ru/practicum/shareit/request/controller/ItemRequestController.java
> + * TODO Sprint add-item-requests.
исправил

2024-06-28 07:42 UTC, Jariodson commented on src/main/java/ru/practicum/shareit/request/controller/ItemRequestController.java
> +@ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
исправил

2024-06-28 07:43 UTC, Jariodson commented on src/main/java/ru/practicum/shareit/request/controller/ItemRequestController.java
> +    public ResponseEntity<ItemRequestDto> getRequestById(@RequestHeader("X-Sharer-User-Id") Long userId,
исправил

2024-06-28 07:43 UTC, Jariodson commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> + * TODO Sprint add-item-requests.
исправил

2024-06-28 14:59 UTC, YazykovMikhail approved these changes

2024-06-29 09:03 UTC, merged